version: "3"
output: interleaved
dotenv: [".env.local"]
vars:
  INDENT: 4
  REL_PATH: "{{ relPath .USER_WORKING_DIR .ROOT_DIR }}"
  VENV_DIR: ".venv"
  PYTHON_MAIN: '{{ joinPath "./src" "agent.py" }}'

tasks:
  post_create:
    desc: "Runs after this template is instantiated as a Sandbox or Bootstrap"
    cmds:
      - echo 'To try the new agent directly in your terminal:'
      - echo ''
      - echo '{{ indent .INDENT "cd" }} {{ .REL_PATH }}'
      - echo '{{ indent .INDENT "uv sync" }}'
      - echo '{{ indent .INDENT "uv run" }} {{ .PYTHON_MAIN }} download-files'
      - echo '{{ indent .INDENT "uv run" }} {{ .PYTHON_MAIN }} console'
      - echo ''
      - echo 'To deploy your agent to LiveKit cloud:'
      - echo ''
      - echo '{{ indent .INDENT "lk agent create" }}'
      - echo ''
      - task: set_agent_name_if_present
      - task: help_open_sandbox_if_present

  set_agent_name_if_present:
    status:
      - test -z "$LIVEKIT_AGENT_NAME"
    cmds:
      - |
        old="WorkerOptions("
        new="WorkerOptions(agent_name=\"{{ .LIVEKIT_AGENT_NAME }}\", "
        file="{{ .PYTHON_MAIN }}"
        tmp="$(mktemp)"
        while IFS= read -r line; do
          printf '%s\n' "${line//$old/$new}" >> "$tmp"
        done < "$file"
        mv "$tmp" "$file"

  help_open_sandbox_if_present:
    status:
      - test -z "$LIVEKIT_SANDBOX_ID"
    cmds:
      - echo 'To chat with your running agent, visit:'
      - echo ''
      - echo '{{ indent .INDENT "https://" }}{{ .LIVEKIT_SANDBOX_ID }}.sandbox.livekit.io'
      - echo ''

  install:
    desc: "Bootstrap application for local development"
    cmds:
      - "uv sync"
  dev:
    interactive: true
    cmds:
      - "uv run src/agent.py dev"

  # ==================== Infrastructure Tasks ====================
  
  db:up:
    desc: "Start PostgreSQL and Redis containers"
    cmds:
      - docker-compose up -d postgres redis
      - echo "â³ Waiting for services to be healthy..."
      - sleep 3
      - docker-compose ps

  db:down:
    desc: "Stop all containers"
    cmds:
      - docker-compose down

  db:reset:
    desc: "Stop containers and remove volumes (DESTRUCTIVE)"
    cmds:
      - docker-compose down -v
      - echo "ðŸ—‘ï¸  All data removed"

  db:migrate:
    desc: "Run database migrations"
    cmds:
      - uv run alembic upgrade head

  db:migrate:create:
    desc: "Create a new migration (usage: task db:migrate:create -- 'description')"
    cmds:
      - uv run alembic revision --autogenerate -m "{{.CLI_ARGS}}"

  db:seed:
    desc: "Seed database with sample appointments"
    cmds:
      - uv run python src/scripts/seed_db.py --clear

  # ==================== One-Command Setup ====================
  
  setup:
    desc: "ðŸš€ Full setup: containers + migrate + seed"
    cmds:
      - task: install
      - task: db:up
      - echo "â³ Waiting for database to be ready..."
      - sleep 2
      - task: db:migrate
      - task: db:seed
      - echo ""
      - echo "âœ… Environment ready!"
      - echo "   Run 'task dev' to start the agent"

  start-calls:
    desc: "Run the call initiator script"
    cmds:
      - uv run python src/start_calls.py

